<?php

namespace Database\Seeders;

use App\Models\Algorithm\NaiveBayes;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class NaiveBayesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $data = collect(
            [
                [
                    "id" => 1,
                    "uniform" => "seragam",
                    "hst" => 59.0,
                    "texture" => "keras",
                    "is_dry" => "simpan kering",
                    "is_dirty" => "tidak ada",
                    "is_rotting" => "tidak busuk",
                    "is_damage" => "tidak rusak",
                    "moisture_content" => 77.451,
                    "diameter" => 2.3265,
                    "mutu_class" => 2,
                ],
                [
                    "id" => 2,
                    "uniform" => "seragam",
                    "hst" => 59.0,
                    "texture" => "keras",
                    "is_dry" => "simpan kering",
                    "is_dirty" => "tidak ada",
                    "is_rotting" => "tidak busuk",
                    "is_damage" => "tidak rusak",
                    "moisture_content" => 77.951,
                    "diameter" => 2.221,
                    "mutu_class" => 2,
                ],
                [
                    "id" => 3,
                    "uniform" => "seragam",
                    "hst" => 59.0,
                    "texture" => "keras",
                    "is_dry" => "simpan kering",
                    "is_dirty" => "tidak ada",
                    "is_rotting" => "tidak busuk",
                    "is_damage" => "tidak rusak",
                    "moisture_content" => 78.83,
                    "diameter" => 1.825,
                    "mutu_class" => 2,
                ],
                [
                    "id" => 4,
                    "uniform" => "seragam",
                    "hst" => 59.0,
                    "texture" => "keras",
                    "is_dry" => "simpan kering",
                    "is_dirty" => "tidak ada",
                    "is_rotting" => "tidak busuk",
                    "is_damage" => "tidak rusak",
                    "moisture_content" => 77.708,
                    "diameter" => 2.604,
                    "mutu_class" => 2,
                ],
                [
                    "id" => 5,
                    "uniform" => "seragam",
                    "hst" => 59.0,
                    "texture" => "keras",
                    "is_dry" => "simpan kering",
                    "is_dirty" => "tidak ada",
                    "is_rotting" => "tidak busuk",
                    "is_damage" => "tidak rusak",
                    "moisture_content" => 76.42,
                    "diameter" => 2.44,
                    "mutu_class" => 2,
                ],
                [
                    "id" => 6,
                    "uniform" => "seragam",
                    "hst" => 59.0,
                    "texture" => "cukup keras",
                    "is_dry" => "simpan kering",
                    "is_dirty" => "tidak ada",
                    "is_rotting" => "tidak busuk",
                    "is_damage" => "rusak",
                    "moisture_content" => 80.552,
                    "diameter" => 2.437,
                    "mutu_class" => 1,
                ],
                [
                    "id" => 7,
                    "uniform" => "seragam",
                    "hst" => 56.0,
                    "texture" => "keras",
                    "is_dry" => "simpan kering",
                    "is_dirty" => "tidak ada",
                    "is_rotting" => "tidak busuk",
                    "is_damage" => "tidak rusak",
                    "moisture_content" => 78.117,
                    "diameter" => 2.2135,
                    "mutu_class" => 2,
                ],
                [
                    "id" => 8,
                    "uniform" => "seragam",
                    "hst" => 56.0,
                    "texture" => "keras",
                    "is_dry" => "simpan kering",
                    "is_dirty" => "tidak ada",
                    "is_rotting" => "tidak busuk",
                    "is_damage" => "tidak rusak",
                    "moisture_content" => 79.328,
                    "diameter" => 1.504,
                    "mutu_class" => 2,
                ],
                [
                    "id" => 9,
                    "uniform" => "seragam",
                    "hst" => 56.0,
                    "texture" => "keras",
                    "is_dry" => "simpan kering",
                    "is_dirty" => "tidak ada",
                    "is_rotting" => "busuk",
                    "is_damage" => "tidak rusak",
                    "moisture_content" => 80.47,
                    "diameter" => 0.828,
                    "mutu_class" => 2,
                ],
                [
                    "id" => 10,
                    "uniform" => "seragam",
                    "hst" => 56.0,
                    "texture" => "keras",
                    "is_dry" => "simpan kering",
                    "is_dirty" => "tidak ada",
                    "is_rotting" => "busuk",
                    "is_damage" => "tidak rusak",
                    "moisture_content" => 80.961,
                    "diameter" => 1.5005,
                    "mutu_class" => 2,
                ],
                [
                    "id" => 11,
                    "uniform" => "seragam",
                    "hst" => 56.0,
                    "texture" => "keras",
                    "is_dry" => "simpan kering",
                    "is_dirty" => "tidak ada",
                    "is_rotting" => "tidak busuk",
                    "is_damage" => "tidak rusak",
                    "moisture_content" => 80.699,
                    "diameter" => 1.4345,
                    "mutu_class" => 2,
                ],
                [
                    "id" => 12,
                    "uniform" => "seragam",
                    "hst" => 56.0,
                    "texture" => "cukup keras",
                    "is_dry" => "simpan kering",
                    "is_dirty" => "tidak ada",
                    "is_rotting" => "tidak busuk",
                    "is_damage" => "tidak rusak",
                    "moisture_content" => 78.128,
                    "diameter" => 2.5445,
                    "mutu_class" => 2,
                ],
                [
                    "id" => 13,
                    "uniform" => "seragam",
                    "hst" => 65.0,
                    "texture" => "cukup keras",
                    "is_dry" => "simpan kering",
                    "is_dirty" => "tidak ada",
                    "is_rotting" => "tidak busuk",
                    "is_damage" => "tidak rusak",
                    "moisture_content" => 79.041,
                    "diameter" => 2.6025,
                    "mutu_class" => 1,
                ],
                [
                    "id" => 14,
                    "uniform" => "seragam",
                    "hst" => 65.0,
                    "texture" => "cukup keras",
                    "is_dry" => "simpan kering",
                    "is_dirty" => "tidak ada",
                    "is_rotting" => "tidak busuk",
                    "is_damage" => "tidak rusak",
                    "moisture_content" => 82.206,
                    "diameter" => 2.048,
                    "mutu_class" => 1,
                ],
                [
                    "id" => 15,
                    "uniform" => "seragam",
                    "hst" => 65.0,
                    "texture" => "cukup keras",
                    "is_dry" => "simpan kering",
                    "is_dirty" => "tidak ada",
                    "is_rotting" => "tidak busuk",
                    "is_damage" => "tidak rusak",
                    "moisture_content" => 81.659,
                    "diameter" => 2.327,
                    "mutu_class" => 1,
                ],
                [
                    "id" => 16,
                    "uniform" => "seragam",
                    "hst" => 65.0,
                    "texture" => "keras",
                    "is_dry" => "simpan kering",
                    "is_dirty" => "tidak ada",
                    "is_rotting" => "tidak busuk",
                    "is_damage" => "tidak rusak",
                    "moisture_content" => 77.142,
                    "diameter" => 1.604,
                    "mutu_class" => 1,
                ],
                [
                    "id" => 17,
                    "uniform" => "seragam",
                    "hst" => 65.0,
                    "texture" => "keras",
                    "is_dry" => "simpan kering",
                    "is_dirty" => "tidak ada",
                    "is_rotting" => "tidak busuk",
                    "is_damage" => "tidak rusak",
                    "moisture_content" => 74.577,
                    "diameter" => 1.838,
                    "mutu_class" => 1,
                ],
                [
                    "id" => 18,
                    "uniform" => "seragam",
                    "hst" => 65.0,
                    "texture" => "keras",
                    "is_dry" => "simpan kering",
                    "is_dirty" => "tidak ada",
                    "is_rotting" => "tidak busuk",
                    "is_damage" => "tidak rusak",
                    "moisture_content" => 76.741,
                    "diameter" => 2.103,
                    "mutu_class" => 1,
                ],
                [
                    "id" => 19,
                    "uniform" => "seragam",
                    "hst" => 59.0,
                    "texture" => "keras",
                    "is_dry" => "simpan kering",
                    "is_dirty" => "tidak ada",
                    "is_rotting" => "tidak busuk",
                    "is_damage" => "tidak rusak",
                    "moisture_content" => 79.161,
                    "diameter" => 1.4385,
                    "mutu_class" => 2,
                ],
                [
                    "id" => 20,
                    "uniform" => "seragam",
                    "hst" => 59.0,
                    "texture" => "keras",
                    "is_dry" => "simpan kering",
                    "is_dirty" => "tidak ada",
                    "is_rotting" => "tidak busuk",
                    "is_damage" => "tidak rusak",
                    "moisture_content" => 76.496,
                    "diameter" => 1.6055,
                    "mutu_class" => 2,
                ],
                [
                    "id" => 21,
                    "uniform" => "seragam",
                    "hst" => 59.0,
                    "texture" => "keras",
                    "is_dry" => "simpan kering",
                    "is_dirty" => "tidak ada",
                    "is_rotting" => "busuk",
                    "is_damage" => "tidak rusak",
                    "moisture_content" => 77.009,
                    "diameter" => 1.1075,
                    "mutu_class" => 2,
                ],
                [
                    "id" => 22,
                    "uniform" => "seragam",
                    "hst" => 59.0,
                    "texture" => "keras",
                    "is_dry" => "simpan kering",
                    "is_dirty" => "tidak ada",
                    "is_rotting" => "tidak busuk",
                    "is_damage" => "tidak rusak",
                    "moisture_content" => 78.334,
                    "diameter" => 1.3255,
                    "mutu_class" => 2,
                ],
                [
                    "id" => 23,
                    "uniform" => "seragam",
                    "hst" => 59.0,
                    "texture" => "keras",
                    "is_dry" => "simpan kering",
                    "is_dirty" => "tidak ada",
                    "is_rotting" => "tidak busuk",
                    "is_damage" => "tidak rusak",
                    "moisture_content" => 77.512,
                    "diameter" => 1.3265,
                    "mutu_class" => 2,
                ],
                [
                    "id" => 24,
                    "uniform" => "seragam",
                    "hst" => 59.0,
                    "texture" => "keras",
                    "is_dry" => "simpan kering",
                    "is_dirty" => "tidak ada",
                    "is_rotting" => "tidak busuk",
                    "is_damage" => "tidak rusak",
                    "moisture_content" => 78.197,
                    "diameter" => 1.7185,
                    "mutu_class" => 2,
                ],
                [
                    "id" => 25,
                    "uniform" => "seragam",
                    "hst" => 60.0,
                    "texture" => "keras",
                    "is_dry" => "simpan kering",
                    "is_dirty" => "tidak ada",
                    "is_rotting" => "tidak busuk",
                    "is_damage" => "tidak rusak",
                    "moisture_content" => 77.034,
                    "diameter" => 1.543,
                    "mutu_class" => 1,
                ],
                [
                    "id" => 26,
                    "uniform" => "seragam",
                    "hst" => 60.0,
                    "texture" => "keras",
                    "is_dry" => "simpan kering",
                    "is_dirty" => "tidak ada",
                    "is_rotting" => "tidak busuk",
                    "is_damage" => "tidak rusak",
                    "moisture_content" => 79.017,
                    "diameter" => 1.612,
                    "mutu_class" => 1,
                ],
                [
                    "id" => 27,
                    "uniform" => "seragam",
                    "hst" => 60.0,
                    "texture" => "keras",
                    "is_dry" => "simpan kering",
                    "is_dirty" => "tidak ada",
                    "is_rotting" => "tidak busuk",
                    "is_damage" => "tidak rusak",
                    "moisture_content" => 75.726,
                    "diameter" => 1.611,
                    "mutu_class" => 1,
                ],
                [
                    "id" => 28,
                    "uniform" => "seragam",
                    "hst" => 60.0,
                    "texture" => "cukup keras",
                    "is_dry" => "simpan kering",
                    "is_dirty" => "tidak ada",
                    "is_rotting" => "tidak busuk",
                    "is_damage" => "rusak",
                    "moisture_content" => 81.265,
                    "diameter" => 1.0495,
                    "mutu_class" => 1,
                ],
                [
                    "id" => 29,
                    "uniform" => "seragam",
                    "hst" => 60.0,
                    "texture" => "keras",
                    "is_dry" => "simpan kering",
                    "is_dirty" => "tidak ada",
                    "is_rotting" => "tidak busuk",
                    "is_damage" => "tidak rusak",
                    "moisture_content" => 79.721,
                    "diameter" => 1.8245,
                    "mutu_class" => 1,
                ],
                [
                    "id" => 30,
                    "uniform" => "seragam",
                    "hst" => 60.0,
                    "texture" => "keras",
                    "is_dry" => "simpan kering",
                    "is_dirty" => "tidak ada",
                    "is_rotting" => "tidak busuk",
                    "is_damage" => "tidak rusak",
                    "moisture_content" => 78.098,
                    "diameter" => 1.545,
                    "mutu_class" => 1,
                ],
                [
                    "id" => 31,
                    "uniform" => "seragam",
                    "hst" => 57.0,
                    "texture" => "keras",
                    "is_dry" => "simpan kering",
                    "is_dirty" => "tidak ada",
                    "is_rotting" => "tidak busuk",
                    "is_damage" => "tidak rusak",
                    "moisture_content" => 80.654,
                    "diameter" => 1.828,
                    "mutu_class" => 2,
                ],
                [
                    "id" => 32,
                    "uniform" => "seragam",
                    "hst" => 57.0,
                    "texture" => "keras",
                    "is_dry" => "simpan kering",
                    "is_dirty" => "tidak ada",
                    "is_rotting" => "tidak busuk",
                    "is_damage" => "tidak rusak",
                    "moisture_content" => 82.781,
                    "diameter" => 1.721,
                    "mutu_class" => 2,
                ],
                [
                    "id" => 33,
                    "uniform" => "seragam",
                    "hst" => 57.0,
                    "texture" => "keras",
                    "is_dry" => "simpan kering",
                    "is_dirty" => "tidak ada",
                    "is_rotting" => "tidak busuk",
                    "is_damage" => "tidak rusak",
                    "moisture_content" => 78.342,
                    "diameter" => 1.436,
                    "mutu_class" => 2,
                ],
                [
                    "id" => 34,
                    "uniform" => "seragam",
                    "hst" => 57.0,
                    "texture" => "keras",
                    "is_dry" => "simpan kering",
                    "is_dirty" => "tidak ada",
                    "is_rotting" => "tidak busuk",
                    "is_damage" => "tidak rusak",
                    "moisture_content" => 81.23,
                    "diameter" => 2.2185,
                    "mutu_class" => 2,
                ],
                [
                    "id" => 35,
                    "uniform" => "seragam",
                    "hst" => 57.0,
                    "texture" => "keras",
                    "is_dry" => "simpan kering",
                    "is_dirty" => "tidak ada",
                    "is_rotting" => "tidak busuk",
                    "is_damage" => "tidak rusak",
                    "moisture_content" => 79.562,
                    "diameter" => 1.5005,
                    "mutu_class" => 2,
                ],
                [
                    "id" => 36,
                    "uniform" => "seragam",
                    "hst" => 57.0,
                    "texture" => "keras",
                    "is_dry" => "simpan kering",
                    "is_dirty" => "tidak ada",
                    "is_rotting" => "tidak busuk",
                    "is_damage" => "tidak rusak",
                    "moisture_content" => 80.089,
                    "diameter" => 1.8335,
                    "mutu_class" => 2,
                ],
                [
                    "id" => 37,
                    "uniform" => "seragam",
                    "hst" => 58.0,
                    "texture" => "keras",
                    "is_dry" => "simpan kering",
                    "is_dirty" => "tidak ada",
                    "is_rotting" => "tidak busuk",
                    "is_damage" => "tidak rusak",
                    "moisture_content" => 79.782,
                    "diameter" => 1.216,
                    "mutu_class" => 2,
                ],
                [
                    "id" => 38,
                    "uniform" => "seragam",
                    "hst" => 58.0,
                    "texture" => "keras",
                    "is_dry" => "simpan kering",
                    "is_dirty" => "tidak ada",
                    "is_rotting" => "tidak busuk",
                    "is_damage" => "tidak rusak",
                    "moisture_content" => 77.039,
                    "diameter" => 1.72,
                    "mutu_class" => 2,
                ],
                [
                    "id" => 39,
                    "uniform" => "seragam",
                    "hst" => 58.0,
                    "texture" => "keras",
                    "is_dry" => "simpan kering",
                    "is_dirty" => "tidak ada",
                    "is_rotting" => "tidak busuk",
                    "is_damage" => "tidak rusak",
                    "moisture_content" => 81.902,
                    "diameter" => 1.936,
                    "mutu_class" => 2,
                ],
                [
                    "id" => 40,
                    "uniform" => "seragam",
                    "hst" => 58.0,
                    "texture" => "keras",
                    "is_dry" => "simpan kering",
                    "is_dirty" => "tidak ada",
                    "is_rotting" => "tidak busuk",
                    "is_damage" => "tidak rusak",
                    "moisture_content" => 78.189,
                    "diameter" => 1.2175,
                    "mutu_class" => 2,
                ],
                [
                    "id" => 41,
                    "uniform" => "seragam",
                    "hst" => 58.0,
                    "texture" => "keras",
                    "is_dry" => "simpan kering",
                    "is_dirty" => "tidak ada",
                    "is_rotting" => "tidak busuk",
                    "is_damage" => "tidak rusak",
                    "moisture_content" => 79.268,
                    "diameter" => 1.105,
                    "mutu_class" => 2,
                ],
                [
                    "id" => 42,
                    "uniform" => "seragam",
                    "hst" => 58.0,
                    "texture" => "keras",
                    "is_dry" => "simpan kering",
                    "is_dirty" => "tidak ada",
                    "is_rotting" => "tidak busuk",
                    "is_damage" => "tidak rusak",
                    "moisture_content" => 78.263,
                    "diameter" => 1.215,
                    "mutu_class" => 2,
                ],
                [
                    "id" => 43,
                    "uniform" => "seragam",
                    "hst" => 66.0,
                    "texture" => "keras",
                    "is_dry" => "simpan kering",
                    "is_dirty" => "tidak ada",
                    "is_rotting" => "tidak busuk",
                    "is_damage" => "tidak rusak",
                    "moisture_content" => 79.29,
                    "diameter" => 0.6105,
                    "mutu_class" => 1,
                ],
                [
                    "id" => 44,
                    "uniform" => "seragam",
                    "hst" => 66.0,
                    "texture" => "keras",
                    "is_dry" => "simpan kering",
                    "is_dirty" => "tidak ada",
                    "is_rotting" => "tidak busuk",
                    "is_damage" => "tidak rusak",
                    "moisture_content" => 80.129,
                    "diameter" => 2.2175,
                    "mutu_class" => 1,
                ],
                [
                    "id" => 45,
                    "uniform" => "seragam",
                    "hst" => 66.0,
                    "texture" => "keras",
                    "is_dry" => "simpan kering",
                    "is_dirty" => "tidak ada",
                    "is_rotting" => "tidak busuk",
                    "is_damage" => "tidak rusak",
                    "moisture_content" => 76.842,
                    "diameter" => 1.719,
                    "mutu_class" => 1,
                ],
                [
                    "id" => 46,
                    "uniform" => "seragam",
                    "hst" => 66.0,
                    "texture" => "keras",
                    "is_dry" => "simpan kering",
                    "is_dirty" => "tidak ada",
                    "is_rotting" => "tidak busuk",
                    "is_damage" => "tidak rusak",
                    "moisture_content" => 78.764,
                    "diameter" => 2.0025,
                    "mutu_class" => 1,
                ],
                [
                    "id" => 47,
                    "uniform" => "seragam",
                    "hst" => 66.0,
                    "texture" => "keras",
                    "is_dry" => "simpan kering",
                    "is_dirty" => "tidak ada",
                    "is_rotting" => "tidak busuk",
                    "is_damage" => "tidak rusak",
                    "moisture_content" => 78.632,
                    "diameter" => 1.936,
                    "mutu_class" => 1,
                ],
                [
                    "id" => 48,
                    "uniform" => "seragam",
                    "hst" => 66.0,
                    "texture" => "keras",
                    "is_dry" => "simpan kering",
                    "is_dirty" => "tidak ada",
                    "is_rotting" => "tidak busuk",
                    "is_damage" => "tidak rusak",
                    "moisture_content" => 81.286,
                    "diameter" => 2.001,
                    "mutu_class" => 1,
                ],
            ]
        );

        $data->each(fn($item) => NaiveBayes::create($item));
    }
}
